# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95834b6aa25e107467aa1225ac2c681bc827cce2737da2f0e7a3c82935312a9ff8eb3e7ed1f89b8aff674ee61adfc1c0c6ffc676606f9674bea0528f3ce146e3

test:
  secret_key_base: ab667bee58b1329a16610730f47f95bd651e6802ae3a51031c2ba7f35c12648d4fb95d563e623e7fcb804d175498709ef236eda1de5bddf8c2edbe0dfaec23d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
